import test from 'node:test';import assert from 'node:assert/strict';import {deedBaseline,saveSingleDeed,mergeLegal,deedTransition,publishedDeeds} from '../src/deed-workflow';
const mkt={id:'mkt',name:'MKT',role:'MKT'},bs={id:'bs',name:'Arianti',role:'BS'},head={id:'head',name:'Dellatra',role:'HEAD_BS'};
const input={id:'test',type:'establishment',deedNumber:'001',deedDate:'2020-01-01',ministerialDecreeNumber:'SK001',ministerialDecreeDate:'2020-01-02',stakeholders:[{name:'Budi',sharePercentage:100,email:'budi@example.com',mobilePhone:'081234567890',primaryCapital:100,idType:'KTP',idNumber:'3171010101900001'}]};
test('two-step deed approval gates published shareholders and freezes pending data',()=>{const legal=mergeLegal({}, {deeds:[{...input,review:{status:'APPROVED'}}]});assert.equal(legal.deeds[0].review.status,'DRAFT');assert.equal(publishedDeeds(legal).length,0);let deed=deedTransition(legal.deeds[0],'SUBMIT',mkt,{revision:1,documentId:'file'});assert.throws(()=>mergeLegal({deeds:[deed]},{deeds:[{...deed,remarks:'changed'}]}));assert.throws(()=>deedTransition(deed,'APPROVE',head,{revision:2}));assert.throws(()=>deedTransition(deed,'CHECK',mkt,{revision:2}));deed=deedTransition(deed,'CHECK',bs,{revision:2});assert.throws(()=>deedTransition(deed,'APPROVE',{...head,role:'LEGAL'},{revision:3}));deed=deedTransition(deed,'APPROVE',head,{revision:3});assert.equal(publishedDeeds({deeds:[deed]})[0].stakeholders[0].sharePercentage,100);const edited=mergeLegal({deeds:[deed]},{deeds:[{...deed,remarks:'revision'}]}).deeds[0];assert.equal(edited.review.status,'DRAFT');assert.equal(publishedDeeds({deeds:[edited]})[0].remarks,undefined);assert.throws(()=>mergeLegal({deeds:[deed]},{deeds:[]}));});
test('rejection requires a reason, preserves history and can be resubmitted',()=>{let deed=mergeLegal({}, {deeds:[input]}).deeds[0];deed=deedTransition(deed,'SUBMIT',mkt,{revision:1,documentId:'file'});assert.throws(()=>deedTransition(deed,'REJECT',bs,{revision:2}));deed=deedTransition(deed,'REJECT',bs,{revision:2,comments:'Nomor salah'});assert.equal(deed.review.rejectionReason,'Nomor salah');assert.equal(deed.review.submittedById,'mkt');deed=deedTransition(deed,'SUBMIT',mkt,{revision:3,documentId:'file'});assert.equal(deed.review.status,'PENDING_CHECK');assert.equal(deed.review.rejectionReason,null);assert.equal(deed.reviewHistory.length,3);assert.throws(()=>deedTransition(deed,'CHECK',bs,{revision:3}));});

test('deed can pass submit, check and approval without attachment',()=>{let deed=mergeLegal({}, {deeds:[input]}).deeds[0];deed=deedTransition(deed,'SUBMIT',mkt,{revision:1});assert.equal(deed.review.documentId,undefined);deed=deedTransition(deed,'CHECK',bs,{revision:2});deed=deedTransition(deed,'APPROVE',head,{revision:3});assert.equal(publishedDeeds({deeds:[deed]}).length,1);});

test('saving a selected deed leaves unrelated invalid dated deeds untouched',()=>{const invalid={id:'other',deedNumber:'OTHER',deedDate:'3333-12-31',review:{status:'DRAFT',revision:1}};const prior={deeds:[invalid]};const result=saveSingleDeed(prior,input.id,input);assert.deepEqual(result.deeds[0],invalid);let target=result.deeds.find((d:any)=>d.id===input.id);target=deedTransition(target,'SUBMIT',mkt,{revision:1});assert.equal(target.review.status,'PENDING_CHECK');assert.equal(result.deeds[0].review.status,'DRAFT');});

test('amendment comparison uses approved prior deeds and freezes the submitted baseline',()=>{const approved={...input,approvedSnapshot:structuredClone(input),approvedAt:'2026-01-01'};const next={...input,id:'amendment',type:'amendment',remarkCategoryId:'SHARES',deedDate:'2025-01-01',ministerialDecreeDate:'2025-01-02'};const legal={deeds:[approved,{...input,id:'unapproved',deedDate:'2024-01-01'}]};const baseline=deedBaseline(legal,next);assert.equal(baseline.id,input.id);let d=mergeLegal({}, {deeds:[next]}).deeds[0];d=deedTransition(d,'SUBMIT',mkt,{revision:1,beforeSnapshot:baseline});approved.approvedSnapshot.stakeholders[0].sharePercentage=50;assert.equal(d.review.comparisonBefore.stakeholders[0].sharePercentage,100);d=deedTransition(d,'CHECK',bs,{revision:2});d=deedTransition(d,'APPROVE',head,{revision:3});assert.equal(d.review.comparisonBefore.id,input.id);assert.equal(deedBaseline({deeds:[]},next),null);});
