import 'dotenv/config';
import express,{type Request,type Response,type NextFunction} from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {z} from 'zod';
import {S3Client,PutObjectCommand,GetObjectCommand} from '@aws-sdk/client-s3';
import {getSignedUrl} from '@aws-sdk/s3-request-presigner';
import {all,insert,update,replace,query,transaction,initialize,dataDir,type Query} from './db';
import {seed} from './seed';
import {defaultMasterCatalog,validateMasterCatalog,type MasterCatalog} from '../src/master-catalog';
import {ensure,Problem,modelInput,validateStakeholders,validateFinancials,validateProposal,checklistTemplate,fapNumber,ratios,installment} from './domain';
await initialize();await seed();
await query('INSERT INTO master_data(id,catalog) VALUES(1,$1) ON CONFLICT(id) DO NOTHING',[JSON.stringify(defaultMasterCatalog())]);
async function masterData(q:Query=query){const row=(await q('SELECT catalog,revision FROM master_data WHERE id=1')).rows[0];return {catalog:{...defaultMasterCatalog(),...row.catalog} as MasterCatalog,revision:row.revision};}
let secret=process.env.JWT_SECRET;
if(!secret){if(process.env.NODE_ENV==='production')throw new Error('JWT_SECRET is required in production');const file=path.join(dataDir,'session-secret');try{secret=await fs.readFile(file,'utf8');}catch{secret=crypto.randomBytes(48).toString('hex');await fs.writeFile(file,secret);}}
const jwtSecret=secret;
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');if(req.path.startsWith('/api'))res.setHeader('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin){const origin=new URL(req.headers.origin);if(!['http://127.0.0.1:5173','http://localhost:5173',`http://${req.headers.host}`,process.env.APP_ORIGIN].includes(origin.origin))return next(new Problem(403,'Origin is not allowed'));}next();});
type Actor={id:string,name:string,email:string,role:string};
declare global{namespace Express{interface Request{actor:Actor}}}
const attempts=new Map<string,{count:number,until:number}>();
app.post('/api/v1/auth/login',async(req,res)=>{const key=req.ip||'local',entry=attempts.get(key);ensure(!entry||entry.count<10||entry.until<Date.now(),'Too many login attempts. Try again in 15 minutes.',429);const {email,password}=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const user=(await query('SELECT * FROM users WHERE email=$1',[email.toLowerCase()])).rows[0];if(!user||!await bcrypt.compare(password,user.password_hash)){attempts.set(key,{count:(entry&&entry.until>Date.now()?entry.count:0)+1,until:Date.now()+900000});throw new Problem(401,'Email or password is incorrect');}attempts.delete(key);const actor={id:user.id,name:user.name,email:user.email,role:user.role};res.cookie('los_session',jwt.sign(actor,jwtSecret,{expiresIn:'8h',audience:'los-api'}),{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:28800000,path:'/'});res.json(actor);});
app.post('/api/v1/auth/logout',(_req,res)=>{res.clearCookie('los_session',{path:'/'});res.json({ok:true});});
app.get('/api/v1/health',(_req,res)=>res.json({status:'ok'}));
app.use('/api',async(req,res,next)=>{try{const token=(req.headers.cookie||'').split('; ').find(x=>x.startsWith('los_session='))?.slice(12);ensure(token,'Please sign in',401);const decoded=jwt.verify(token,jwtSecret,{audience:'los-api'}) as Actor;const user=(await query('SELECT id,name,email,role FROM users WHERE id=$1',[decoded.id])).rows[0];ensure(user,'Session is no longer valid',401);req.actor=user;next();}catch(e){next(e instanceof Problem?e:new Problem(401,'Session expired. Please sign in again.'));}});
const permit=(req:Request,roles:string[])=>ensure(roles.includes(req.actor.role),'Your role cannot perform this action',403);
async function application(id:string,q=query){const a=(await all('Application',{id},q))[0];ensure(a,'Application not found',404);return a;}
async function detail(id:string,q=query){const a=await application(id,q);a.legal=(await q('SELECT legal FROM applications WHERE id=$1',[id])).rows[0]?.legal||{};a.customer=(await all('Customer',{id:a.customerId},q))[0];a.pic=(await all('ApplicationPic',{applicationId:id},q))[0]||null;for(const [key,model] of Object.entries({stakeholders:'Stakeholder',projects:'ProjectContract',bankReferences:'BankReference',financialStatements:'FinancialStatement',documentChecks:'DocumentChecklist',approvalLogs:'ApprovalLog'}))a[key]=await all(model,{applicationId:id},q);a.proposal=(await all('FinancingProposal',{applicationId:id},q))[0]||null;if(a.proposal){a.proposal.units=await all('FinancingUnitItem',{proposalId:a.proposal.id},q);const timing=(await masterData(q)).catalog.paymentMethod.find(x=>x.value===a.proposal.paymentMethod)?.timing;a.proposal.estimatedInstallment=installment({...a.proposal,paymentMethod:timing==='advance'?'In Advance':'In Arrear'});}for(const d of a.documentChecks)d.files=await all('DocumentFile',{checklistId:d.id},q);a.financialStatements.sort((x:any,y:any)=>x.fiscalYear-y.fiscalYear);a.ratios=a.financialStatements.map((r:any)=>({fiscalYear:r.fiscalYear,...ratios(r)}));a.approvalLogs.sort((x:any,y:any)=>new Date(y.actionTimestamp).getTime()-new Date(x.actionTimestamp).getTime());a.signoffs=(await q('SELECT * FROM review_signoffs WHERE application_id=$1',[id])).rows;return a;}
app.get('/api/v1/auth/me',(req,res)=>res.json(req.actor));
app.get('/api/v1/master-data',async(_req,res)=>res.json(await masterData()));
app.put('/api/v1/master-data',async(req,res)=>{let catalog:MasterCatalog;try{catalog=validateMasterCatalog(req.body.catalog);}catch(e:any){throw new Problem(422,e.message);}const result=await transaction(async q=>{await q('SELECT id FROM master_data WHERE id=1 FOR UPDATE');const previous=await masterData(q);ensure(req.body.revision===previous.revision,'Master data telah berubah. Muat ulang lalu simpan kembali.',409);for(const [key,rows] of Object.entries(previous.catalog))for(const row of rows)ensure(catalog[key].some(x=>x.value===row.value),'Data lama harus dipertahankan. Gunakan status tidak aktif untuk menonaktifkan pilihan.');await q('UPDATE master_data SET catalog=$1,revision=revision+1 WHERE id=1',[JSON.stringify(catalog)]);return masterData(q);});res.json(result);});
app.get('/api/v1/customers',async(_req,res)=>res.json(await all('Customer')));
app.post('/api/v1/customers',async(req,res)=>{permit(req,['MKT']);const data=modelInput('Customer',req.body,['companyName','companyType','nib','npwp']);ensure(/^\d{13}$/.test(data.nib),'NIB must contain 13 digits');ensure(/^\d{15,16}$/.test(data.npwp.replace(/\D/g,'')),'NPWP must contain 15 or 16 digits');res.status(201).json(await insert('Customer',data));});
app.get('/api/v1/applications',async(req,res)=>{const rows=await query(`SELECT a.*,c.company_name,c.company_type,(SELECT count(*)::integer FROM document_checklists d WHERE d.application_id=a.id AND d.status='VERIFIED') AS verified_docs,(SELECT count(*)::integer FROM document_checklists d WHERE d.application_id=a.id) AS total_docs,p.financing_value,p.tenor_months,p.financing_method FROM applications a JOIN customers c ON c.id=a.customer_id LEFT JOIN financing_proposals p ON p.application_id=a.id ORDER BY a.created_at DESC`);res.json(rows.rows);});
const appRequired=['branchCode','customerStatus','companyAddress','city','province','postalCode','phoneFax','email','mainBusiness','locationStatus','repaymentSource','industrySegment','businessRole'];
app.post('/api/v1/applications',async(req,res)=>{permit(req,['MKT']);const body=modelInput('Application',req.body,appRequired);z.string().email().parse(body.email);const customerId=z.string().uuid().parse(req.body.customerId);ensure((await all('Customer',{id:customerId})).length,'Customer not found',404);const a=await transaction(async q=>{const year=new Date().getUTCFullYear();const n=(await q('INSERT INTO fap_sequences(year,value) VALUES($1,1) ON CONFLICT(year) DO UPDATE SET value=fap_sequences.value+1 RETURNING value',[year])).rows[0].value;const a=await insert('Application',{...body,customerId,fapNumber:fapNumber(n)},q);for(const doc of (await masterData(q)).catalog.documents.filter(x=>x.active))await insert('DocumentChecklist',{applicationId:a.id,documentCode:doc.value,documentName:doc.name,assignedRole:doc.role,isMandatory:doc.required},q);await insert('ApprovalLog',{applicationId:a.id,actionBy:req.actor.name,userRole:req.actor.role,previousStatus:'DRAFT',newStatus:'DRAFT',comments:'Application created'},q);return a;});res.status(201).json(a);});
app.get('/api/v1/document-desk',async(_req,res)=>{const rows=await query("SELECT d.id AS checklist_id,d.application_id,d.document_code,d.document_name,d.assigned_role,d.is_mandatory,d.status,a.fap_number,c.company_name,(SELECT count(*)::integer FROM document_files f WHERE f.checklist_id=d.id) AS file_count FROM document_checklists d JOIN applications a ON a.id=d.application_id JOIN customers c ON c.id=a.customer_id ORDER BY CASE d.status WHEN 'REJECTED' THEN 0 WHEN 'PENDING' THEN 1 WHEN 'UPLOADED' THEN 2 ELSE 3 END,a.created_at DESC,d.document_name");res.json(rows.rows);});
app.get('/api/v1/applications/:id',async(req,res)=>res.json(await detail(String(req.params.id))));
const editable=(a:any,req:Request,ca=false)=>{permit(req,ca?['MKT','CA']:['MKT']);ensure(req.actor.role==='CA'?a.status==='IN_CA_LEGAL_REVIEW':['DRAFT','RETURNED'].includes(a.status),'This application is locked at its current workflow stage',409);};
app.put('/api/v1/applications/:id/page-1',async(req,res)=>{const id=String(req.params.id);await transaction(async q=>{await q('SELECT id FROM applications WHERE id=$1 FOR UPDATE',[id]);const a=await application(id,q);editable(a,req);const body=req.body;
 if(body.profile){const data=modelInput('Application',body.profile,appRequired);z.string().email().parse(data.email);await update('Application',id,data,q);}
 if(body.pic){const p=modelInput('ApplicationPic',body.pic,['picName','position','phone','email','currentAddress','city','province','postalCode']);z.string().email().parse(p.email);await replace('ApplicationPic','applicationId',id,[p],q);}
 if(body.stakeholders){const rows=z.array(z.any()).max(100).parse(body.stakeholders).map(x=>modelInput('Stakeholder',x,['name','position','stakeholderType','nationalityType','idNumber','shareAmount','sharePercentage','email','mobilePhone','primaryCapital']));if(rows.length)validateStakeholders(rows);await replace('Stakeholder','applicationId',id,rows,q);const d=(await all('DocumentChecklist',{applicationId:id,documentCode:'EKITAS'},q))[0];await update('DocumentChecklist',d.id,{isMandatory:rows.some(s=>s.stakeholderType==='INDIVIDUAL'&&s.nationalityType==='WNA')},q);}
 for(const [key,model,required] of [['projects','ProjectContract',['projectOwner','projectLocation','projectRole','contractStatus']],['bankReferences','BankReference',['bankOrFinInstitution','currency','creditFacility','monthlyInstallment','yearStarted','interestRate','paymentRecord','facilityStatus']]] as const)if(body[key])await replace(model,'applicationId',id,z.array(z.any()).max(100).parse(body[key]).map(x=>modelInput(model,x,[...required])),q);
 await insert('ApprovalLog',{applicationId:id,actionBy:req.actor.name,userRole:req.actor.role,previousStatus:a.status,newStatus:a.status,comments:'Profile and business information updated'},q);
 });res.json(await detail(id));});
app.put('/api/v1/applications/:id/page-2',async(req,res)=>{const id=String(req.params.id);await transaction(async q=>{await q('SELECT id FROM applications WHERE id=$1 FOR UPDATE',[id]);const a=await application(id,q);editable(a,req,true);
 if(req.body.proposal){const p=modelInput('FinancingProposal',req.body.proposal,['facilityPurpose','financingMethod','currency','financingValue','downPaymentValue','interestRate','tenorMonths','paymentMethod']);const units=z.array(z.any()).max(100).parse(req.body.proposal.units).map(x=>modelInput('FinancingUnitItem',x,['brand','unitCategory','modelName','quantity','unitPrice','totalPrice']));validateProposal(p,units);let existing=(await all('FinancingProposal',{applicationId:id},q))[0];existing=existing?await update('FinancingProposal',existing.id,p,q):await insert('FinancingProposal',{...p,applicationId:id},q);await replace('FinancingUnitItem','proposalId',existing.id,units,q);}
 if(req.body.financialStatements){const rows=z.array(z.any()).max(3).parse(req.body.financialStatements).map(x=>modelInput('FinancialStatement',x,['fiscalYear','isAudited','currentAssets','nonCurrentAssets','totalAssets','currentLiabilities','nonCurrentLiabilities','totalLiabilities','equity','totalLiabAndEquity','revenue','grossMargin','operatingMargin','tax','netIncome']));validateFinancials(rows);await replace('FinancialStatement','applicationId',id,rows,q);}
 await q('DELETE FROM review_signoffs WHERE application_id=$1 AND role=$2',[id,'CA']);await insert('ApprovalLog',{applicationId:id,actionBy:req.actor.name,userRole:req.actor.role,previousStatus:a.status,newStatus:a.status,comments:'Financing and financial statements updated'},q);
 });res.json(await detail(id));});
app.put('/api/v1/applications/:id/page-legal',async(req,res)=>{const id=String(req.params.id);await transaction(async q=>{await q('SELECT id FROM applications WHERE id=$1 FOR UPDATE',[id]);const a=await application(id,q);ensure(req.actor.role==='MKT'&&['DRAFT','RETURNED'].includes(a.status)||req.actor.role==='LEGAL'&&a.status==='IN_CA_LEGAL_REVIEW','Legal information is locked at this workflow stage',403);const parties=z.object({representative:z.string().max(1000).optional(),shareholder:z.string().max(1000).optional(),shareholders:z.array(z.string().max(1000)).max(100).optional(),companyShareholder:z.string().max(1000).optional()});const deed=z.object({id:z.string().max(100).optional(),type:z.enum(['establishment','amendment']).optional(),source:z.string().max(100).optional(),createdAt:z.string().datetime().optional(),deedNumber:z.string().max(1000).optional(),deedDate:z.string().date().nullable().optional(),ministerialDecreeNumber:z.string().max(1000).optional(),ministerialDecreeDate:z.string().date().nullable().optional(),remarks:z.string().max(10000).optional(),infoAdded:z.boolean().optional(),parties:parties.optional(),stakeholders:z.array(z.record(z.string(),z.any())).max(100).optional()});const legal=z.object({deeds:z.array(deed).max(100).optional(),hiddenDeedIds:z.array(z.string().max(100)).max(100).optional(),selectedDeedId:z.string().max(100).optional(),selectedDeed:z.enum(['establishment','amendment']).optional(),establishment:deed.optional(),amendment:deed.optional(),representative:z.string().max(1000).optional(),shareholder:z.string().max(1000).optional(),companyShareholder:z.string().max(1000).optional()}).parse(req.body.legal);if(req.body.stakeholders){const rows=z.array(z.any()).max(100).parse(req.body.stakeholders).map(x=>modelInput('Stakeholder',x,['name','position','stakeholderType','nationalityType','idNumber','shareAmount','sharePercentage','email','mobilePhone','primaryCapital']));if(rows.length)validateStakeholders(rows);await replace('Stakeholder','applicationId',id,rows,q);const d=(await all('DocumentChecklist',{applicationId:id,documentCode:'EKITAS'},q))[0];await update('DocumentChecklist',d.id,{isMandatory:rows.some(s=>s.stakeholderType==='INDIVIDUAL'&&s.nationalityType==='WNA')},q);}await q('UPDATE applications SET legal=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2',[JSON.stringify(legal),id]);await q('DELETE FROM review_signoffs WHERE application_id=$1 AND role=$2',[id,'LEGAL']);await insert('ApprovalLog',{applicationId:id,actionBy:req.actor.name,userRole:req.actor.role,previousStatus:a.status,newStatus:a.status,comments:'Legal information updated'},q);});res.json(await detail(id));});
app.get('/api/v1/applications/:id/checklist',async(req,res)=>res.json((await detail(String(req.params.id))).documentChecks));
const s3=process.env.S3_BUCKET?new S3Client({region:process.env.S3_REGION||'ap-southeast-1',endpoint:process.env.S3_ENDPOINT||undefined,forcePathStyle:!!process.env.S3_ENDPOINT,credentials:{accessKeyId:process.env.S3_ACCESS_KEY_ID||'',secretAccessKey:process.env.S3_SECRET_ACCESS_KEY||''}}):null;
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:1}});
app.post('/api/v1/applications/:id/documents/upload',upload.single('file'),async(req,res)=>{permit(req,['MKT','BS']);const id=String(req.params.id);const file=req.file;ensure(file,'Choose a file');const actual=file.buffer.subarray(0,8);const valid=(file.mimetype==='application/pdf'&&actual.subarray(0,5).toString()==='%PDF-')||(file.mimetype==='image/png'&&actual.equals(Buffer.from([137,80,78,71,13,10,26,10])))||(file.mimetype==='image/jpeg'&&actual[0]===255&&actual[1]===216&&actual[2]===255);ensure(valid,'Upload a valid PDF, PNG or JPEG file');
 const result=await transaction(async q=>{await q('SELECT id FROM applications WHERE id=$1 FOR UPDATE',[id]);const a=await application(id,q);ensure(!['APPROVED','REJECTED','CREDIT_COMMITTEE_REVIEW'].includes(a.status),'Documents are locked at this stage',409);const d=(await all('DocumentChecklist',{id:req.body.checklistId,applicationId:id},q))[0];ensure(d,'Checklist item not found',404);const key=crypto.randomUUID();if(s3)await s3.send(new PutObjectCommand({Bucket:process.env.S3_BUCKET,Key:key,Body:file.buffer,ContentType:file.mimetype,ServerSideEncryption:'AES256'}));else{await fs.mkdir(path.join(dataDir,'files'),{recursive:true});await fs.writeFile(path.join(dataDir,'files',key),file.buffer);}
 const f=await insert('DocumentFile',{checklistId:d.id,fileName:path.basename(file.originalname),fileKey:key,fileSize:file.size,mimeType:file.mimetype,uploadedBy:req.actor.name},q);await update('DocumentChecklist',d.id,{status:'UPLOADED',checkedByMkt:true,checkedByBs:false,checkedByCa:false,checkedByLegal:false},q);await q('DELETE FROM review_signoffs WHERE application_id=$1',[id]);await q('INSERT INTO document_events(application_id,checklist_id,actor,action,details) VALUES($1,$2,$3,$4,$5)',[id,d.id,req.actor.name,'UPLOAD',JSON.stringify({fileName:f.fileName})]);return f;});res.status(201).json(result);});
app.patch('/api/v1/applications/:id/checklist/:checklistId/verify',async(req,res)=>{permit(req,['BS','CA','LEGAL']);const body=z.object({department:z.enum(['BS','CA','LEGAL']),isVerified:z.boolean(),registrationDate:z.string().date().nullable().optional(),expiredDate:z.string().date().nullable().optional(),dataSummary:z.string().max(10000).optional(),notes:z.string().max(10000).optional()}).parse(req.body);ensure(body.department===req.actor.role,'Cannot verify for another department',403);const id=String(req.params.id);await transaction(async q=>{await q('SELECT id FROM applications WHERE id=$1 FOR UPDATE',[id]);const a=await application(id,q);ensure(req.actor.role==='BS'?a.status==='SUBMITTED_TO_BS':a.status==='IN_CA_LEGAL_REVIEW','Verification is unavailable at this workflow stage',409);const d=(await all('DocumentChecklist',{id:String(req.params.checklistId),applicationId:id},q))[0];ensure(d,'Checklist item not found',404);ensure((await all('DocumentFile',{checklistId:d.id},q)).length,'Upload a document before verification');if(body.isVerified&&body.expiredDate)ensure(body.expiredDate>=new Date().toISOString().slice(0,10),'An expired document cannot be verified');if(body.expiredDate&&body.registrationDate)ensure(body.expiredDate>=body.registrationDate,'Expiry must follow registration');const key={BS:'checkedByBs',CA:'checkedByCa',LEGAL:'checkedByLegal'}[body.department];const updated:any={...body,[key]:body.isVerified};if(body.department===d.assignedRole)updated.status=body.isVerified?'VERIFIED':'REJECTED';await update('DocumentChecklist',d.id,updated,q);await q('DELETE FROM review_signoffs WHERE application_id=$1 AND role=$2',[id,req.actor.role]);await q('INSERT INTO document_events(application_id,checklist_id,actor,action,details) VALUES($1,$2,$3,$4,$5)',[id,d.id,req.actor.name,body.isVerified?'VERIFY':'REJECT',JSON.stringify(body)]);});res.json(await detail(id));});
app.get('/api/v1/files/:id/url',async(req,res)=>{const f=(await all('DocumentFile',{id:String(req.params.id)}))[0];ensure(f,'File not found',404);const url=s3?await getSignedUrl(s3,new GetObjectCommand({Bucket:process.env.S3_BUCKET,Key:f.fileKey,ResponseContentDisposition:'inline'}),{expiresIn:900}):`/api/v1/files/${f.id}/content?token=${jwt.sign({fileId:f.id,userId:req.actor.id},jwtSecret,{expiresIn:'15m',audience:'los-file'})}`;res.json({url,expiresIn:900});});
app.get('/api/v1/files/:id/content',async(req,res)=>{let token:any;try{token=jwt.verify(String(req.query.token),jwtSecret,{audience:'los-file'});}catch{throw new Problem(403,'Document link has expired');}ensure(token.fileId===req.params.id&&token.userId===req.actor.id,'Invalid document link',403);const f=(await all('DocumentFile',{id:String(req.params.id)}))[0];ensure(f,'File not found',404);res.setHeader('Content-Type',f.mimeType);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(f.fileName)}`);res.sendFile(path.join(dataDir,'files',f.fileKey),{dotfiles:'allow'});});
app.get('/api/v1/applications/:id/document-events',async(req,res)=>{await application(String(req.params.id));res.json((await query('SELECT * FROM document_events WHERE application_id=$1 ORDER BY created_at DESC',[req.params.id])).rows);});
app.post('/api/v1/applications/:id/transition',async(req,res)=>{const id=String(req.params.id);const {action,comments}=z.object({action:z.enum(['SUBMIT_TO_BS','VERIFY_BS','START_REVIEW','RECOMMEND_CA','RECOMMEND_LEGAL','APPROVE_COMMITTEE','REJECT_COMMITTEE','RETURN']),comments:z.string().trim().max(10000).default('')}).parse(req.body);
 await transaction(async q=>{await q('SELECT id FROM applications WHERE id=$1 FOR UPDATE',[id]);const a=await detail(id,q);let status=a.status;
 const docs=(role?:string)=>a.documentChecks.filter((d:any)=>d.isMandatory&&(!role||d.assignedRole===role));
 const verified=(role?:string)=>{const missing=docs(role).filter((d:any)=>d.status!=='VERIFIED'||(d.expiredDate&&new Date(d.expiredDate).toISOString().slice(0,10)<new Date().toISOString().slice(0,10)));ensure(!missing.length,`Verify required documents: ${missing.map((d:any)=>d.documentName).join(', ')}`);};
 if(action==='SUBMIT_TO_BS'){permit(req,['MKT']);ensure(['DRAFT','RETURNED'].includes(status),'Only draft or returned applications can be submitted',409);ensure(a.pic,'Complete the contact information');validateStakeholders(a.stakeholders);ensure(a.proposal,'Complete financing proposal');validateProposal(a.proposal,a.proposal.units);validateFinancials(a.financialStatements,true);const missing=docs().filter((d:any)=>d.documentCode!=='LEGAL_OPINION'&&!d.files.length);ensure(!missing.length,`Upload required documents: ${missing.map((d:any)=>d.documentName).join(', ')}`);status='SUBMITTED_TO_BS';}
 if(action==='VERIFY_BS'){permit(req,['BS']);ensure(status==='SUBMITTED_TO_BS','Application must be submitted to BS',409);verified('BS');status='BS_VERIFIED';}
 if(action==='START_REVIEW'){permit(req,['BS']);ensure(status==='BS_VERIFIED','BS verification is required',409);status='IN_CA_LEGAL_REVIEW';}
 if(action==='RECOMMEND_CA'||action==='RECOMMEND_LEGAL'){const role=action==='RECOMMEND_CA'?'CA':'LEGAL';permit(req,[role]);ensure(status==='IN_CA_LEGAL_REVIEW','Application must be in CA & Legal review',409);verified(role);if(role==='CA')validateFinancials(a.financialStatements,true);await q('INSERT INTO review_signoffs(application_id,role,actor) VALUES($1,$2,$3) ON CONFLICT(application_id,role) DO UPDATE SET actor=excluded.actor,signed_at=now()',[id,role,req.actor.name]);const signs=(await q('SELECT * FROM review_signoffs WHERE application_id=$1',[id])).rows;if(signs.length===2){verified();status='CREDIT_COMMITTEE_REVIEW';}}
 if(action==='APPROVE_COMMITTEE'||action==='REJECT_COMMITTEE'){permit(req,['COMMITTEE']);ensure(status==='CREDIT_COMMITTEE_REVIEW','Application must be at credit committee',409);if(action==='APPROVE_COMMITTEE')verified();else ensure(comments,'Provide a reason for rejection');status=action==='APPROVE_COMMITTEE'?'APPROVED':'REJECTED';}
 if(action==='RETURN'){permit(req,['BS','CA','LEGAL','COMMITTEE']);const allowed:Record<string,string[]>={BS:['SUBMITTED_TO_BS','BS_VERIFIED'],CA:['IN_CA_LEGAL_REVIEW'],LEGAL:['IN_CA_LEGAL_REVIEW'],COMMITTEE:['CREDIT_COMMITTEE_REVIEW']};ensure(allowed[req.actor.role].includes(status),'Cannot return from this workflow stage',409);ensure(comments,'Provide a reason for returning the application');await q('DELETE FROM review_signoffs WHERE application_id=$1',[id]);status='RETURNED';}
 await update('Application',id,{status},q);await insert('ApprovalLog',{applicationId:id,actionBy:req.actor.name,userRole:req.actor.role,previousStatus:a.status,newStatus:status,comments:comments||action.replaceAll('_',' ')},q);
 });res.json(await detail(id));});
app.use('/api',(_req,_res,next)=>next(new Problem(404,'Endpoint not found')));
app.use(express.static(path.resolve('dist')));app.get('/{*path}',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));
app.use((error:any,req:Request,res:Response,_next:NextFunction)=>{let status=error.status||500,message=error.message,errors=error.errors||[];if(error instanceof z.ZodError){status=422;message='Validation failed';errors=error.issues.map(x=>({field:x.path.join('.'),detail:x.message}));}else if(error.code==='23505'){status=409;message='A record with these unique details already exists';}else if(['23514','23502','22001','22003','22007','22P02'].includes(error.code)){status=422;message='One or more fields contain an invalid value';}else if(error.code==='23503'){status=422;message='Referenced record was not found';}else if(error instanceof multer.MulterError){status=422;message=error.code==='LIMIT_FILE_SIZE'?'File exceeds the 20 MB limit':error.message;}if(status>=500){console.error(error);message='An unexpected server error occurred';}res.status(status).type('application/problem+json').json({type:'about:blank',title:message,status,statusCode:status,error:status===422?'Unprocessable Entity':message,message,errors,timestamp:new Date().toISOString()});});
const port=Number(process.env.PORT||3001);app.listen(port,'127.0.0.1',()=>console.log(`LiuGong API running at http://127.0.0.1:${port}`));
