import {validateWrite} from './input-validation';
const menuFor=(path:string)=>path==='/master-data'||path.startsWith('/master-data/')?'master-data':path==='/customers'||path.startsWith('/customers/')?'customers':path==='/applications'||path.startsWith('/applications/')?'applications':path==='/document-desk'||path.startsWith('/document-desk/')?'document-desk':path==='/notifications'||path.startsWith('/notifications/')?'notifications':path==='/activity'||path.startsWith('/activity/')?'activity':null;
async function remoteApi(path:string,method='GET',body?:any){const form=body instanceof FormData;let response:Response;try{response=await fetch('/api/v1'+path,{method,credentials:'same-origin',headers:body&&!form?{'Content-Type':'application/json'}:{},body:body?(form?body:JSON.stringify(body)):undefined});}catch{throw new Error('Cannot connect to the server. Please try again.');}const text=await response.text();let data:any;try{data=JSON.parse(text);}catch{throw new Error('The server is temporarily unavailable. Please try again.');}if(!response.ok)throw new Error(data.errors?.length?data.errors.map((x:any)=>`${x.field}: ${x.detail}`).join('\n'):data.message||'Request failed');
 const menu=path==='/applications'||path.startsWith('/applications/')||path==='/master-data'||path.startsWith('/master-data/')?null:menuFor(path);
 if(menu&&method==='GET'){try{const r=await fetch(`/api/v1/workspace-data/${menu}`,{credentials:'same-origin'});if(r.ok){const entries=await r.json();const saved=entries.map((x:any)=>x.payload).filter(Boolean);if(Array.isArray(data))data=[...saved,...data];else if(menu==='master-data'&&saved.length)data=saved[0];}}catch{}}
 if(menu&&method!=='GET'&&!(body instanceof FormData)){const saved=await fetch(`/api/v1/workspace-data/${menu}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload:data})});if(!saved.ok)throw new Error('Perubahan lokal tersimpan, tetapi MySQL gagal menyimpan data menu.');}
 return data;}

export async function api(path:string,method='GET',body?:any){validateWrite(path,method,body);return remoteApi(path,method,body);}
